[package]
name = "particle-simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flo_canvas = "0.3.1"
flo_draw = "0.3.1"
rand = "0.8.5"
ordered-float = "3.4.0"
